version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  application:
    container_name: web-learners
    image: testdevhari/web-learners-task-application
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
      SECRET_KEY: "SOME_PRIVATE_KEY"
      PORT: 3000
    ports:
      - "3000:3000"
    restart: always

volumes:
  pgdata:
